let videoData = [
  {
    id: 1,
    title: "Ruhsora Emm - Under The Influence (Chris Brown)",
    channel: "X-Faktor O'zbekiston",
    channelPhoto:
      "https://yt3.ggpht.com/Om0mmOcWC-yPkRyAaoF00KZrnbNEQbTg-zK7Ebk62UfqjHGiY_1UtaR9ul9qfb8EyGI27bYHHh4=s68-c-k-c0x00ffffff-no-rj",
    views: "1 млн просмотров",
    uploaded: "1 год назад",
    duration: "9:22",
    thumbnail: "thumbnails/ruxsora.avif",
    category: "Music",
    src: "https://www .youtube.com/embed/8RBm0qKOmHY",
  },
  {
    id: 2,
    title: '"Yo‘q" deyishni bilish | Abdusattor Abduraximov',
    channel: "Maqsad Club",
    channelPhoto:
      "https://yt3.ggpht.com/BV5IwOdY0X_eLqssWRI3cc_w73WfzDAAhBxXjWHVruyVKKyYCg4mtBgB0bsmm30i_488Bkym8A=s68-c-k-c0x00ffffff-no-rj",
    views: "52K",
    uploaded: "2 hafta oldin",
    duration: "5:15",
    thumbnail: "thumbnails/yoq-deyish.avif",
    category: "Shaxsiy rivojlanish",
    src: "https://www.youtube.com/embed/VaKz4Jbe6C0",
  },
  {
    id: 3,
    title:
      "Sun’iy intellektni 5 karra yaxshiroq ishlating | Xurshid Maroziqov | Birfoiz",
    channel: "birfoizbilim",
    channelPhoto:
      "https://yt3.ggpht.com/R-bmxKk1oz327JRWlcmigEC6i7WflcFk7zzlODvYGLZ2iZZi2l-kyR2_Ac2ZPXB4TrE8GWrUYQ=s68-c-k-c0x00ffffff-no-rj",
    views: "71K",
    uploaded: "1 oy oldin",
    duration: "21:17",
    thumbnail: "thumbnails/ai-5x.avif",
    category: "Texnologiya",
    src: "https://www.youtube.com/embed/Oxe8LZYK31w",
  },
  {
    id: 4,
    title: "Tirik kitob - Xayrulla Asatov - Тирик китоб",
    channel: "Xayrulla Asatov",
    channelPhoto:
      "https://yt3.ggpht.com/0YTYDIIniz5lCR0vKyXoBvbAZ2lkIr9iW8nFp_TjiQKveU0wd-ClNhoMHxlvvG5OvdV6oUW5kpQ=s68-c-k-c0x00ffffff-no-rj",
    views: "381K",
    uploaded: "5 kun oldin",
    duration: "4:53",
    thumbnail: "thumbnails/tirik-kitob.avif",
    category: "Madaniyat",
    src: "https://www.youtube.com/embed/bdEYgtmzQdk",
  },
  {
    id: 5,
    title: "Siz bilmagan Minecraft",
    channel: "UPG",
    channelPhoto:
      "https://yt3.ggpht.com/2Qw5nLGk206cx1UzvsbJZh_kcW6gAtQnHT0bniVrl4bqG1RMrSJH-B-J0UX8Xltljv0RExpD=s68-c-k-c0x00ffffff-no-rj",
    views: "49K",
    uploaded: "3 kun oldin",
    duration: "16:24",
    thumbnail: "thumbnails/minecraft.avif",
    category: "O'yinlar",
    src: "https://www.youtube.com/embed/CgZ5ukSgubc",
  },
  {
    id: 6,
    title: "Sizni Aqlliroq Qiluvchi 15 ta Odat!",
    channel: "Nurli Media",
    channelPhoto:
      "https://yt3.ggpht.com/ytc/AIdro_lTB6EGmAFhNDtpfRzK52Xsl4RtieuMLl1qj4uYcuv7Mw=s68-c-k-c0x00ffffff-no-rj",
    views: "338K",
    uploaded: "1 yil oldin",
    duration: "17:26",
    thumbnail: "thumbnails/aqlliroq.avif",
    category: "Shaxsiy rivojlanish",
    src: "https://www.youtube.com/embed/cA1Q5bFY5Z8",
  },
  {
    id: 7,
    title:
      "DANGASALIKKA QARSHI 10 ta Oddiy Ammo Kuchli Texnika (100% Ishlaydi!)",
    channel: "DAVRONBEK TURDIEV",
    channelPhoto:
      "https://yt3.ggpht.com/NgMI5B2Sw4YiMFP4LQw5bNq4sTsBioMDXckxjxaOUTIfdkAS85R2Uzfhv5XAaEbY_Uk6pHUdfQ=s68-c-k-c0x00ffffff-no-rj",
    views: "170K",
    uploaded: "3 hafta oldin",
    duration: "27:51",
    thumbnail: "thumbnails/dangasalikka-qarshi.avif",
    category: "Motivatsiya",
    src: "https://www.youtube.com/embed/uul53emqf10",
  },
  {
    id: 8,
    title: "18 Years Old Cristiano Ronaldo was INSANE",
    channel: "VALENTINO PRODUCTIONS",
    channelPhoto:
      "https://yt3.ggpht.com/vyfJhgtTbO-NC8ymcLHCdtO7MhIIwReE2AxyP4jEljAdhh5MBOK1bQWeLheebwYW-3YttvNUrA=s68-c-k-c0x00ffffff-no-rj",
    views: "10M",
    uploaded: "1 yil oldin",
    duration: "15:48",
    thumbnail: "thumbnails/ronaldo.avif",
    category: "Sport",
    src: "https://www.youtube.com/embed/XXYbVpkI-UY",
  },
  {
    id: 9,
    title: "Xcho & timmate & Пабло - Нарекай (Official Audio)",
    channel: "Glass Cage",
    channelPhoto:
      "https://yt3.googleusercontent.com/ytc/AIdro_k0v74Er7Bwu18QBstky50t1UVNX6oKTUtPx63nBcdnP3U=s160-c-k-c0x00ffffff-no-rj",
    views: "1.01M",
    uploaded: "3 oy oldin",
    duration: "2:43",
    thumbnail: "thumbnails/hq720.jpg",
    category: "Music",
    src: "https://youtu.be/8noTy0l4Plg?t=1055",
  },
  {
    id: 10,
    title: "Xcho & Пабло & Mr Lambo - Моя печаль (Official Audio)",
    channel: "Glass Cage",
    channelPhoto:
      "https://yt3.googleusercontent.com/ytc/AIdro_k0v74Er7Bwu18QBstky50t1UVNX6oKTUtPx63nBcdnP3U=s160-c-k-c0x00ffffff-no-rj",
    views: "1.01M",
    uploaded: "3 oy oldin",
    duration: "2:43",
    thumbnail: "thumbnails/hq720 (1).jpg",
    category: "Music",
    src: "https://youtu.be/SVCJU999nGY",
  },
  {
    id: 11,
    title: "FULL UC LOBBY VA WOW LOBBILAR QILAMIZ",
    channel: "JANAGA PUBGMOBILE ",
    channelPhoto:
      "https://yt3.googleusercontent.com/zvabrWgHcWL0vO3FCYfkPyQrHkNVTzE8DL518LHjFVhicI1IQRfl-L2Mb-xG1SXuLBX_XbPO=s160-c-k-c0x00ffffff-no-rj",
    views: "2.9K",
    uploaded: "5 kun oldin",
    duration: "5:12:17",
    thumbnail: "thumbnails/pubg.jpg",
    category: "O'yinlar",
    src: "https://youtu.be/_lGwx2dTwjA",
  },
  {
    id: 12,
    title:
      "3.000.000 SO'M YUTISH UCHUN KRUGDAN OHIRGI BO'LIB CHIQ! Unwanted Boys…",
    channel: "ABDUJABBOROV__7 -  UNWANTED BOYS",
    channelPhoto:
      "https://yt3.googleusercontent.com/1VddnzudOBTDvWLjO-_nOJ8pkNcA1wm6-46uBrj_7thtGWNQzBHxCC_b8AhIpI2wtlwUR8JZOg=s160-c-k-c0x00ffffff-no-rj",
    views: "2.9K",
    uploaded: "3 kun oldin",
    duration: "19:32",
    thumbnail: "thumbnails/maxresdefault.jpg",
    category: "Sport",
    src: "https://youtu.be/-trlp5atQHY",
  },
  {
    id: 13,
    title:
      "Vatikandagi uchrashuv va HAMASning oʻldirilgan qoʻmondoni – 19-may dayjest",
    channel: "KunUZ",
    channelPhoto:
      "https://yt3.googleusercontent.com/1VddnzudOBTDvWLjO-_nOJ8pkNcA1wm6-46uBrj_7thtGWNQzBHxCC_b8AhIpI2wtlwUR8JZOg=s160-c-k-c0x00ffffff-no-rj",
    views: "189K",
    uploaded: "1 oy oldin",
    duration: "19:32",
    thumbnail: "thumbnails/isroil.jpg",
    category: "News",
    src: "https://youtu.be/dmMKV5V6v0g",
  },
  {
    id: 14,
    title: "Dunyodagi eng zamonaviy texnologiyalar top 25",
    channel: "KunUZ",
    channelPhoto:
      "https://yt3.googleusercontent.com/ytc/AIdro_kyPyLPu7EwCsGlnPk81WIMIwgI2VjfI0b5RjjkBqiuwdw=s160-c-k-c0x00ffffff-no-rj",
    views: "132K",
    uploaded: "7 yil oldin",
    duration: "10:25",
    thumbnail: "thumbnails/texnik.jpg",
    category: "Texnologiya",
    src: "https://youtu.be/dmMKV5V6v0g",
  },
  {
    id: 15,
    title: "Siz bilmagan o'zbek madaniy me'rosi | Madaniyat | Xuddi shunday",
    channel: "Xuddi shunday",
    channelPhoto:
      "https://yt3.googleusercontent.com/ujNWVPNGrlVSwKoUDJPk9mPatjkxg9CeB-JUScs5gFjECMMDcSOXyoeJPWZ6Y_07HZ_3_IyTZg=s160-c-k-c0x00ffffff-no-rj",
    views: "8.8K",
    uploaded: "1 yil oldin",
    duration: "15:18",
    thumbnail: "thumbnails/madni.jpg",
    category: "News",
    src: "https://youtu.be/dmMKV5V6v0g",
  },
  {
    id: 16,
    title: "Zubi - sugar [official audio] (prod anatu)",
    channel: "dojang",
    channelPhoto:
      "https://yt3.googleusercontent.com/1ftVekXWaUbPdnU1YK-_wY3Xv4ol48Q9A3OrudZgeJktDun4KegyrNMxOfns3RAi3RohUJUGWj8=s160-c-k-c0x00ffffff-no-rj",
    views: "41M",
    uploaded: "4 yil oldin",
    duration: "3:26",
    thumbnail: "thumbnails/zubi.jpg",
    category: "Music",
    src: "https://youtu.be/g6g2-eo4bXY?list=RDMM",
  },
  {
    id: 17,
    title: "My TDM secret for headshots 😤🎯 | I9 - 14900K + RTX 4070 🔥",
    channel: "TDR DADDY",
    channelPhoto:
      "https://yt3.googleusercontent.com/KHjlAkmFL1y3Klh57LfLG_jcuN03sJpc0fRiVdFXbMFZWQsrwb_wvRPvrjeoWQvUfJKQP2UYFg=s160-c-k-c0x00ffffff-no-rj",
    views: "22K",
    uploaded: "3 hafta oldin",
    duration: "3:03",
    thumbnail: "thumbnails/pubg1.jpg",
    category: "O'yinlar",
    src: "https://youtu.be/9LF8_APhS0c",
  },
  {
    id: 18,
    title: "Indilla Enigma",
    channel: "Kamro",
    channelPhoto:
      "https://yt3.googleusercontent.com/1ftVekXWaUbPdnU1YK-_wY3Xv4ol48Q9A3OrudZgeJktDun4KegyrNMxOfns3RAi3RohUJUGWj8=s160-c-k-c0x00ffffff-no-rj",
    views: "19M",
    uploaded: "1 yil oldin",
    duration: "4:57",
    thumbnail: "thumbnails/indilla.jpg",
    category: "Music",
    src: "https://youtu.be/e5bH2eX_RN8",
  },
  {
    id: 19,
    title: "Trump's budget bill is closer to becoming law",
    channel: "LIVEKENS 5: Your San Antonio News Source",
    channelPhoto:
      "https://yt3.googleusercontent.com/nERF4CPBVvkdmqaq2pq3Wv-VqDLcf1MjtTJRjmmgijjWhsSvcclERaT7YdslqBOIWh1HWRchoA=s160-c-k-c0x00ffffff-no-rj",
    views: "387K",
    uploaded: "1 yil oldin",
    duration: "0:28",
    thumbnail: "thumbnails/new.jpg",
    category: "News",
    src: "https://youtu.be/WVyLsOq7MMs",
  },
];
